homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude:  !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 315
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml
  internal_url: !secret base_url
  external_url: !secret base_url

logger:
  default: warning

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  server_port: 8123
  ip_ban_enabled: true
  login_attempts_threshold: 10
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.7
    - ::1

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

recorder:
  db_url: !secret db_url 
  purge_keep_days: 14

history:
logbook:

# Track the sun
sun:

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
alert: !include alerts.yaml

alarmdecoder:
  device:
    type: socket
    host: 192.168.1.27
    port: 10000
  panel_display: on
  zones:
    09:
      name: 'Front Door'
      type: 'door'
      rfid: '0322355'
    10:
      name: 'Garage Door'
      type: 'door'
      rfid: '0402108'
    11:
      name: 'Laundry Room Door'
      type: 'door'
      rfid: '0627375'
    12:
      name: 'Master Bedroom Door'
      type: 'door'
      rfid: '0526985'
    13:
      name: 'Sun Room Door'
      type: 'door'
      rfid: '0358656'
    14:
      name: 'Office Door'
      type: 'door'
      rfid: '0876836'
    15:
      name: 'Foyer Motion'
      type: 'motion'
      rfid: '0518434'
    16:
      name: 'Sun Room Motion'
      type: 'motion'
      rfid: '0505218'
    17:
      name: 'First Floor Smoke Zone'
      type: 'smoke'
      rfid: '0641332'
    18:
      name: 'Second Floor Smoke Zone'
      type: 'smoke'
      rfid: '0571026'
    19:
      name: 'Basement Smoke Zone'
      type: 'smoke'
      rfid: '0119565'

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  device_config: !include zwave_device_config.yaml

weather:
  - platform: darksky
    api_key: !secret dark_sky_secret

sense:
  email: !secret sense_email
  password: !secret sense_password

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

notify:
  - name: Pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key
  - name: Twilio
    platform: twilio_sms
    from_number: !secret twilio_from_number
  - name: Twilio Call
    platform: twilio_call
    from_number: !secret twilio_from_number
  - name: Contact Kyle
    platform: group
    services:
      - service: mobile_app_kyles_iphone
      - service: twilio
        data:
          target: !secret kyle_phone
      - service: twilio_call
        data:
          target: !secret kyle_phone

# device_tracker:
#   - platform: bluetooth_tracker

binary_sensor:
  - platform: template
    sensors:
      first_floor_smoke:
        device_class: smoke
        friendly_name: "First Floor Smoke"
        value_template: >-
          {{ states.sensor.alarm_panel_display.state|trim == "FIRE 17" }}
      second_floor_smoke:
        device_class: smoke
        friendly_name: "Second Floor Smoke"
        value_template: >-
          {{ states.sensor.alarm_panel_display.state|trim == "FIRE 18" }}
      basement_smoke:
        device_class: smoke
        friendly_name: "Basement Smoke"
        value_template: >-
          {{ states.sensor.alarm_panel_display.state|trim == "FIRE 19" }}

shell_command:
  zwave_stick_disco_off: echo -e -n "\x01\x08\x00\xF2\x51\x01\x00\x05\x01\x51" > /dev/ttyACM0
  zwave_stick_disco_on: echo -e -n "\x01\x08\x00\xF2\x51\x01\x01\x05\x01\x50" > /dev/ttyACM0

remote:
  - platform: harmony
    name: Living Room
    host: 192.168.1.20

emulated_roku:
  servers:
    - name: Home Assistant
      host_ip: 192.168.1.6
      listen_port: 8060

camera:
  platform: generic
  still_image_url: http://images.intellicast.com/WxImages/RadarLoop/stc_None_anim.gif
  name: Midwest Weather Radar

rest_command:
  hue_update_dynamic_scene_colors:
    url: !secret hue_update_dynamic_scene_api_uri
    verify_ssl: false
    method: PUT
    payload: '
      {
        "lightstates": {
          "5": { "hue": {{ hue }}, "on": true, "sat": {{ sat }}, "bri": 255 },
          "6": { "hue": {{ hue }}, "on": true, "sat": {{ sat }}, "bri": 255 },
          "9": { "hue": {{ hue }}, "on": true, "sat": {{ sat }}, "bri": 255 },
          "7": { "hue": {{ (((hue|int) + 10923) % 65535) | string }}, "on": true, "sat": {{ sat }}, "bri": 255 },
          "8": { "hue": {{ (((hue|int) + 10923) % 65535) | string }}, "on": true, "sat": {{ sat }}, "bri": 255 },
          "10": { "hue": {{ (((hue|int) + 10923) % 65535) | string }}, "on": true, "sat": {{ sat }}, "bri": 255 }
        }
      }'
  hue_update_dynamic_scene:
    url: !secret hue_update_dynamic_scene_api_uri
    verify_ssl: false
    method: PUT
    payload: '
      {
        "lightstates": {
          "5": { {{ new_lightstate }} },
          "6": { {{ new_lightstate }} },
          "9": { {{ new_lightstate }} },
          "7": { {{ new_lightstate }} },
          "8": { {{ new_lightstate }} },
          "10": { {{ new_lightstate }} }
        }
      }'
  hue_update_kitchen_group_scene_to_dynamic:
    url: !secret hue_update_kitchen_group_action
    verify_ssl: false
    method: PUT
    payload: '{ "scene": "zztOSqWv-nyhFeA" }'
  hue_update_kitchen_group_off:
    url: !secret hue_update_kitchen_group_action
    verify_ssl: false
    method: PUT
    payload: '{ "on": false }'
  hue_update_kitchen_group_on:
    url: !secret hue_update_kitchen_group_action
    verify_ssl: false
    method: PUT
    payload: '{ "on": true }'

system_health:

mobile_app:
